version: '3.9'

services:

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_db:/data/db

  api:
      build: .
      ports:
        - 4000:3004
      
      environment:
        PORT: 3004
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password123
        MONGODB_URI: mongodb://mongo_db:27017
        DB_NAME: my_db
        DB_USER: root 
        DB_PASS: password123
        NAME: Prabhakar
      depends_on:
        - mongo_db 

volumes:
  mongo_db: {}

  

        



